application.title=@project.name@
application.version=@project.version@

spring.datasource.url=jdbc:sqlite:customer-profile.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.sql.init.mode=always
spring.sql.init.schema-locations=file:db/sqlite/customer_personal_information.sql

server.port=5551
server.servlet.context-path=/customer-profile

# Actuator configuration
management.endpoints.web.base-path=/management
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
