application.title=@project.name@
application.version=@project.version@

# Server Configuration
server.port=5555
server.servlet.context-path=/data-aggregator
spring.application.name=data-aggregator

# External Services Configuration
service.customer-profile.url=http://localhost:5551
service.credit-profile.url=http://localhost:5552
service.auth-server.url=http://localhost:5553

# Actuator Configuration
management.endpoints.web.base-path=/management
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

