application.title=@project.name@
application.version=@project.version@

# Server Configuration
server.port=5552
server.servlet.context-path=/credit-profile
spring.application.name=credit-profile

# Database Configuration
database.type=sqlite
spring.datasource.url=jdbc:sqlite:credit-profile.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.sql.init.mode=always
spring.sql.init.schema-locations=file:db/sqlite/credit_information.sql

# Actuator Configuration
management.endpoints.web.base-path=/management
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

